# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CIFAR10": "01_data.cifar.ipynb",
         "CIFAR10DataModule": "01_data.cifar.ipynb",
         "CIFAR10Mandelbrot": "01_data.cifar.ipynb",
         "CIFAR10MandelbrotDataModule": "01_data.cifar.ipynb",
         "MandelBrotFractalTransform": "02_transforms.fractal.ipynb",
         "JuliaFractalTransform": "02_transforms.fractal.ipynb",
         "LitModel": "03_model.dummy.ipynb",
         "BasicBlock": "03a_model.resnet18.ipynb",
         "Bottleneck": "03a_model.resnet18.ipynb",
         "ResNet": "03a_model.resnet18.ipynb",
         "RESNET18": "03a_model.resnet18.ipynb"}

modules = ["data/cifar.py",
           "transforms/fractal.py",
           "model/dummy.py",
           "model/resnet18.py"]

doc_url = "https://satyajitghana.github.io/fractal_augmentation/"

git_url = "https://github.com/satyajitghana/fractal_augmentation/tree/master/"

def custom_doc_links(name): return None
