# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LitModel": "01_model.dummy.ipynb",
         "BasicBlock": "01a_model.resnet18.ipynb",
         "Bottleneck": "01a_model.resnet18.ipynb",
         "ResNet": "01a_model.resnet18.ipynb",
         "RESNET18": "01a_model.resnet18.ipynb",
         "MandelBrotFractalTransform": "02_transforms.fractal.ipynb",
         "JuliaFractalTransform": "02_transforms.fractal.ipynb",
         "CIFAR10": "0a_data.cifar.ipynb",
         "CIFAR10DataModule": "0a_data.cifar.ipynb"}

modules = ["model/dummy.py",
           "model/resnet18.py",
           "transforms/fractal.py",
           "data/cifar.py"]

doc_url = "https://satyajitghana.github.io/fractal_augmentation/"

git_url = "https://github.com/satyajitghana/fractal_augmentation/tree/master/"

def custom_doc_links(name): return None
